name := "MyProject"
version := "1.0"
scalaVersion := "2.10.0"
libraryDependencies += "org.scalactic" %% "scalactic" % "3.0.1"
libraryDependencies += "org.scalatest" %% "scalatest" % "3.0.1"
libraryDependencies += "org.scalaz" %% "scalaz-core" % "7.2.10"
